name: Bespoke Carat Deployment
on:
  push:
    branches:
      - main
      - staging
workflow_dispatch:
jobs: 
  runs-on: ubuntu-latest
  steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set deployment path based on branch
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "Deploying to development environment"
            echo "REMOTE_PATH=/var/www/staging" >> $GITHUB_ENV
            echo ${{ secrets.STAGING_ENV }} >> .env
          else
            echo "Deploying to main environment"
            echo "REMOTE_PATH=/var/www/bespokecarat" >> $GITHUB_ENV
          fi

    - name: Deploy with rsync
        uses: burnett01/rsync-deployments@7.1.0
        with:
          switches: -avz
          path: ./
          remote_path: ${{ env.REMOTE_PATH }}
          remote_host: ${{ secrets.VPS_HOST }}
          remote_user: root
          remote_key: ${{ secrets.VPS_SSH_KEY }}